
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gpxcsv"
version = "0.3.1"
description = 'Convert Garmin GPX file to CSV or JSON'
readme = "README.md"
requires-python = ">=3.7"
license = "MIT"
keywords = []
authors = [{ name = "Marcos Huerta", email = "marcos@marcoshuerta.com" }]
classifiers = [
  'License :: OSI Approved :: MIT License',
  'Operating System :: OS Independent',

  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",


  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = ["lxml"]

[project.urls]
Documentation = "https://github.com/astrowonk/gpxcsv/#readme"
Issues = "https://github.com/astrowonk/gpxcsv/issues"
Source = "https://github.com/astrowonk/gpxcsv"

[project.scripts]
gpxcsv = "gpxcsv.__main__:main"


[tool.hatch.envs.default]
dependencies = ["pytest", "pytest-cov"]
[tool.hatch.envs.default.scripts]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=src --cov=tests"
no-cov = "cov --no-cov"

[[tool.hatch.envs.test.matrix]]
python = ["39", "310", "311","312","313","314"]

[tool.hatch.build.targets.sdist]
exclude = ["/.github"]

[tool.hatch.build.targets.wheel]
packages = ["src/gpxcsv"]

[tool.coverage.run]
branch = true
source = ["src/Tests", 'src/gpxcsv']
command_line = "-m unittest discover -s src"
omit = ["src/gpxcsv/__main__.py"]


[tool.coverage.report]
fail_under = 90
omit = ["src/gpxcsv/__main__.py"]

exclude_also = [
  "def __repr__",
  "if self.debug:",
  "if settings.DEBUG",
  "raise AssertionError",
  "raise NotImplementedError",
  "if 0:",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
  "class .*\\bProtocol\\):",
  "@(abc\\.)?abstractmethod",
]

[tool.ruff]
line-length = 100

[tool.ruff.format]
quote-style = "preserve"
indent-style = "space"
docstring-code-format = true
skip-magic-trailing-comma = true

[tool.ruff.lint]
preview = true
extend-select = [
  "PLE0101",  # return-in-init
  "F811",  # function-redefined
  "F701",  # not-in-loop
  "F702",  # not-in-loop
  "F706",  # return-outside-function
  "F704",  # yield-outside-function
  "B002",  # nonexistent-operator
  "F622",  # too-many-star-expressions
  "PLE0115",  # nonlocal-and-global
  "PLE0117",  # nonlocal-without-binding
  "N805",  # no-self-argument
  "PLE0241",  # duplicate-bases
  "PLE0302",  # unexpected-special-method-signature
  "TID252",  # relative-beyond-top-level
  "F821",  # used-before-assignment
  "F821",  # undefined-variable
  "F822",  # undefined-all-variable
  "PLE0604",  # invalid-all-object
  "PLE0605",  # invalid-all-format
  "PLE0643",  # potential-index-error
  "PLE0704",  # misplaced-bare-raise
  "F901",  # notimplemented-raised
  "PLE1141",  # dict-iter-missing-items
  "PLE1142",  # await-outside-async
  "PLE1205",  # logging-too-many-args
  "PLE1206",  # logging-too-few-args
  "F501",  # truncated-format-string
  "F506",  # mixed-format-string
  "F502",  # format-needs-mapping
  "F524",  # missing-format-string-key
  "F522",  # too-many-format-args
  "F524",  # too-few-format-args
  "PLE1307",  # bad-string-format-type
  "PLE1310",  # bad-str-strip-call
  "PLE1507",  # invalid-envvar-value
  "PLE1519",  # singledispatch-method
  "PLE1520",  # singledispatchmethod-function
  "PLE2502",  # bidirectional-unicode
  "PLE2510",  # invalid-character-backspace
  "PLE2512",  # invalid-character-sub
  "PLE2513",  # invalid-character-esc
  "PLE2514",  # invalid-character-nul
  "PLE2515",  # invalid-character-zero-width-space
  "PLE4703",  # modified-iterating-set
  "F601",  # duplicate-key
  "E703",  # unnecessary-semicolon
  "PLW0602",  # global-variable-not-assigned
  "F841",  # unused-variable
  "PLW0711",  # binary-op-exception
  "F521",  # bad-format-string
  "W605",  # anomalous-backslash-in-string
  "PLW1501",  # bad-open-mode
]

ignore = [
  "N815",  # invalid-name
  "D419",  # empty-docstring
  "D100",  # missing-module-docstring
  "D101",  # missing-class-docstring
  "D103",  # missing-function-docstring
  "E711",  # singleton-comparison
  "E712",  # singleton-comparison
  "E721",  # unidiomatic-typecheck
  "SIM118",  # consider-iterating-dictionary
  "N804",  # bad-classmethod-argument
  "E501",  # line-too-long
  "W291",  # trailing-whitespace
  "W292",  # missing-final-newline
  "W391",  # trailing-newlines
  "E701",  # multiple-statements
  "E702",  # multiple-statements
  "E401",  # multiple-imports
  "I001",  # wrong-import-order
  "I001",  # ungrouped-imports
  "E402",  # wrong-import-position
  "PLC0414",  # useless-import-alias
  "PLC2401",  # non-ascii-name
  "PLC2801",  # unnecessary-dunder-call
  "E731",  # unnecessary-lambda-assignment
  "PLC3002",  # unnecessary-direct-lambda-call
  "F632",  # literal-comparison
  "PLR0124",  # comparison-with-itself
  "PLR0202",  # no-classmethod-decorator
  "PLR0203",  # no-staticmethod-decorator
  "UP004",  # useless-object-inheritance
  "PLR0206",  # property-with-parameters
  "PLR0904",  # too-many-public-methods
  "PLR0911",  # too-many-return-statements
  "PLR0912",  # too-many-branches
  "PLR0913",  # too-many-arguments
  "PLR0914",  # too-many-locals
  "PLR0915",  # too-many-statements
  "PLR0916",  # too-many-boolean-expressions
  "PLR0917",  # too-many-positional-arguments
  "SIM101",  # consider-merging-isinstance
  "PLR1702",  # too-many-nested-blocks
  "SIM108",  # simplifiable-if-statement
  "PLR1704",  # redefined-argument-from-local
  "RET505",  # no-else-return
  "COM818",  # trailing-comma-tuple
  "PLR1708",  # stop-iteration-return
  "RET501",  # inconsistent-return-statements
  "RET502",  # inconsistent-return-statements
  "PLR1711",  # useless-return
  "SIM401",  # consider-using-get
  "C402",  # consider-using-dict-comprehension
  "C401",  # consider-using-set-comprehension
  "SIM210",  # simplifiable-if-expression
  "SIM211",  # simplifiable-if-expression
  "RET506",  # no-else-raise
  "C416",  # unnecessary-comprehension
  "RET508",  # no-else-break
  "RET507",  # no-else-continue
  "UP008",  # super-with-arguments
  "C417",  # consider-using-generator
  "C419",  # use-a-generator
  "PLR1730",  # consider-using-max-builtin
  "SIM115",  # consider-using-with
  "PLR1733",  # unnecessary-dict-index-lookup
  "C405",  # use-list-literal
  "C406",  # use-dict-literal
  "PLR1736",  # unnecessary-list-index-lookup
  "UP028",  # use-yield-from
  "B006",  # dangerous-default-value
  "B018",  # pointless-statement
  "B018",  # expression-not-assigned
  "PIE790",  # unnecessary-pass
  "PLW0108",  # unnecessary-lambda
  "PLW0120",  # useless-else-on-loop
  "S102",  # exec-used
  "S307",  # eval-used
  "PLW0127",  # self-assigning-variable
  "PLW0128",  # redeclared-assigned-name
  "PLW0129",  # assert-on-string-literal
  "B033",  # duplicate-value
  "PLW0131",  # named-expr-without-context
  "PLE0116",  # continue-in-finally
  "B012",  # lost-exception
  "PLW0177",  # nan-comparison
  "F631",  # assert-on-tuple
  "PLW0211",  # bad-staticmethod-argument
  "SLF001",  # protected-access
  "PLW0244",  # redefined-slots-in-subclass
  "PLW0245",  # super-without-brackets
  "E111",  # bad-indentation
  "F403",  # wildcard-import
  "F811",  # reimported
  "PLW0406",  # import-self
  "F404",  # misplaced-future
  "FIX001",  # fixme
  "FIX002",  # fixme
  "FIX003",  # fixme
  "FIX004",  # fixme
  "PLW0603",  # global-statement
  "PLW0604",  # global-at-module-level
  "F401",  # unused-import
  "ARG001",  # unused-argument
  "A001",  # redefined-builtin
  "B023",  # cell-var-from-loop
  "E722",  # bare-except
  "B014",  # duplicate-except
  "TRY302",  # try-except-raise
  "B904",  # raise-missing-from
  "BLE001",  # broad-exception-caught
  "TRY002",  # broad-exception-raised
  "B026",  # keyword-arg-before-vararg
  "G002",  # logging-not-lazy
  "G001",  # logging-format-interpolation
  "G004",  # logging-fstring-interpolation
  "F504",  # unused-format-string-key
  "F524",  # missing-format-argument-key
  "F507",  # unused-format-string-argument
  "F525",  # format-combined-specification
  "F541",  # f-string-without-interpolation
  "F541",  # format-string-without-interpolation
  "ISC001",  # implicit-str-concat
  "Q000",  # inconsistent-quotes
  "UP025",  # redundant-u-string-prefix
  "PLW1507",  # shallow-copy-environ
  "PLW1508",  # invalid-envvar-default
  "PLW1509",  # subprocess-popen-preexec-fn
  "PLW1514",  # unspecified-encoding
  "T100",  # forgotten-debug-statement
  "B019",  # method-cache-max-size-none
  "PLW2101",  # useless-with-lock
  "PIE790",  # unnecessary-ellipsis
  "N999",  # non-ascii-file-name
  "PLW3301",  # nested-min-max
]



